version: '3.2'
services:
  blackbox:
    image: prom/blackbox-exporter:latest
    expose:
    - 9115
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus:/etc/prometheus
    depends_on:
    - blackbox
  web:
    build:
      context: web
    ports:
    - 2112:2112