global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
- job_name: node_exporter
  static_configs:
    - targets: ['node_exporter:9100']