version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_USERNAME=admin
    - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
    - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml