# Maven build
FROM maven:3.5.4-jdk-8-alpine as build

WORKDIR /app
#COPY pom.xml .
#RUN mvn -B -e -C -T 1C org.apache.maven.plugins:maven-dependency-plugin:3.0.2:go-offline
COPY . .
#RUN mvn -B -e -o -T 1C verify
RUN mvn package

# Run the jar
FROM openjdk:8-jre-alpine

WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
CMD ["java", "-jar", "target/example-0.1.0.jar", "server", "config/web.yml"]