FROM maven:3.5.4-jdk-8-alpine as build

# Args
ARG appName
ARG appVersion

WORKDIR /app
COPY pom.xml .
RUN mvn -B -e -C -T 1C org.apache.maven.plugins:maven-dependency-plugin:3.0.2:go-offline
COPY . .
RUN mvn -B -e -o -T 1C verify
RUN mvn package

FROM openjdk:8-jre-alpine
COPY --from=build /app/target/*.jar /app
COPY --from=build /app/config/web.yml /app/web.yml
EXPOSE 8080
CMD ["java", "-jar", "${appName}-${appVersion}.jar", "server", "web.yml"]