FROM golang:1.10 AS builder

# Download and install the latest release of dep
ARG depVersion
ADD https://github.com/golang/dep/releases/download/v${depVersion}/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

# Copy the code from the host and compile it
WORKDIR $GOPATH/src/github.com/lucperkins/prometheus-playground/go-example
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /go-example .

FROM scratch
COPY --from=builder /go-example ./
ENTRYPOINT ["./go-example"]