version: '3.2'
services:
  web:
    build:
      context: web
      cache_from:
      - golang:1.10
      - scratch
      args:
        goPackage: github.com/lucperkins/prometheus-playground/go-example/web
    ports:
    - 2112:2112
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus:/etc/prometheus:ro
    - prometheus_data:/prometheus

volumes:
  prometheus_data: {}
