version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.golang-web
      cache_from:
      - golang:1.10
      - scratch
      args:
        depVersion: 0.4.1
        goPackage: github.com/lucperkins/prometheus-playground/go-example
    ports:
    - 2112:2112