global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: greeting-app
  scrape_interval: 5s
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - greeting:8080