version: '3.2'
services:
  node_exporter:
    image: prom/node-exporter:latest
    expose:
    - 9100
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro